@echo off
echo Configuring Teo sources for the DOS(djgpp) platform...

echo # generated by fixdjgpp.bat > makefile
echo MAKEFILE_INC = makefile.dj >> makefile
echo include makefile.all >> makefile

echo Done!
