@echo off
echo Configuring Teo sources for the DOS(djgpp) platform...

echo # generated by fixdjgpp.bat > makefile
echo MAKEFILE_INC = makefile.dj >> makefile
echo include makefile.all >> makefile

if [%1] == [--quick] goto done

utod .../*.c .../*.h .../*.rc .../*.rh .../*.xpm
utod *.bat .../makefile.* .../*.txt .../*.log .../*.htm*

:done

echo Done!
