@echo off
echo Configuring Teo sources for the Windows (MinGW) platform...

echo # generated by fixmingw.bat > makefile
echo MAKEFILE_INC = makefile.mgw >> makefile
echo include makefile.all >> makefile


lfnfor on
for %%a in (*.*) do echo %%a
lfnfor off

echo Done!
