#!/bin/sh

echo "Configuring Teo sources for the Windows (MinGW) platform..."

echo "# generated by fixmingw.sh" > makefile
echo "MAKEFILE_INC = makefile.mgw" >> makefile
echo "include makefile.all" >> makefile

echo "Done!"
