##################
# compiler flags #
##################

CC = gcc

WFLAGS = -Wall

OFLAGS = -O2

CFLAGS = $(WFLAGS) $(OFLAGS)

linux = 1

################
# target rules #
################

.PHONY: all clean

all: getmemo7 getrom wav2k7

getmemo7: getmemo7.c
	$(CC) -s $(CFLAGS) -o getmemo7 getmemo7.c

getrom: getrom.c
	$(CC) -s $(CFLAGS) -o getrom getrom.c

wav2k7: wav2k7.c
	$(CC) -s $(CFLAGS) -o wav2k7 wav2k7.c

clean:
	rm -f getmemo7 getrom wav2k7
