@echo off

REM ---- Configures Teo sources for the Windows (MinGW) platform ----

echo "Configuring Teo sources for the Windows (MinGW) platform..."

echo # generated by mgwmake.bat > makefile
echo MAKEFILE_INC = makefile.mgw >> makefile
echo include makefile.all >> makefile

REM ---- Creates 'misc\pack\mingw' folder if not exists ----

echo test > misc\pack\mingw\test.txt
if exist misc\pack\mingw\test.txt goto SkipMingw
echo "Creating misc\pack\mingw folder..."
mkdir misc\pack\mingw
goto ExitMingw
:SkipMingw
del misc\pack\mingw\test.txt
:ExitMingw

REM ---- Creates 'misc\pack\mingw\en' folder if not exists ----

echo test > misc\pack\mingw\en\test.txt
if exist misc\pack\mingw\en\test.txt goto SkipEn
echo "Creating misc\pack\mingw\en folder..."
mkdir misc\pack\mingw\en
goto ExitEn
:SkipEn
del misc\pack\mingw\en\test.txt
:ExitEn

REM ---- Creates 'misc\pack\mingw\fr' folder if not exists ----

echo test > misc\pack\mingw\fr\test.txt
if exist misc\pack\mingw\fr\test.txt goto SkipFr
echo "Creating misc\pack\mingw\fr folder..."
mkdir misc\pack\mingw\fr
goto ExitFr
:SkipFr
del misc\pack\mingw\fr\test.txt
:ExitFr

REM ---- Cleans destination directories ----

if exist misc\pack\mingw\fr\makefile.* del misc\pack\mingw\fr\makefile.*
if exist misc\pack\mingw\en\makefile.* del misc\pack\mingw\en\makefile.*
if exist misc\pack\mingw\fr\*.exe del misc\pack\mingw\fr\*.exe
if exist misc\pack\mingw\en\*.exe del misc\pack\mingw\en\*.exe

REM ---- Compiles English version of Teo ----

echo "Creating Teo exec files for Windows setup in English..."

mingw32-make veryclean
mingw32-make EN_LANG=1 PROFILEMODE=1
mingw32-make depend
copy teow.exe misc\pack\mingw\en
copy obj\mingw32\makefile.dep misc\pack\mingw\en\makefile.dep

REM ---- Compiles French version of Teo ----

echo "Creating Teo exec files for Windows setup in French..."

mingw32-make veryclean
mingw32-make FR_LANG=1 PROFILEMODE=1
mingw32-make depend
copy teow.exe misc\pack\mingw\fr
copy obj\mingw32\makefile.dep misc\pack\mingw\fr\makefile.dep

mingw32-make veryclean

REM ---- Compiles English version of CC90HFE ----

echo "Creating windowed CC90HFE exec files for Windows setup in English..."

cd tools
cd cc90hfe

echo Configuring CC90HFE sources for the Windows (MinGW) platform...
echo # generated by fixmingw.bat > makefile
echo MAKEFILE_INC = makefile.mgw >> makefile
echo include makefile.all >> makefile

mingw32-make clean
mingw32-make RELEASE_MODE=1 ENGLISH=1
copy cc90hfe.exe ..\..\misc\pack\mingw\en

REM ---- Compiles French version of CC90HFE ----

echo "Creating windowed CC90HFE exec files for Windows setup in French..."

mingw32-make clean
mingw32-make RELEASE_MODE=1
copy cc90hfe.exe ..\..\misc\pack\mingw\fr

REM ---- Compiles English version of CC90HFE ----

echo "Creating CC90HFE-console  exec files for Windows setup in English..."

mingw32-make clean
mingw32-make RELEASE_MODE=1 CONSOLE_MODE=1 ENGLISH=1
ren  cc90hfe.exe cc90hfe-com.exe
copy cc90hfe-com.exe ..\..\misc\pack\mingw\en
del  cc90hfe-com.exe

REM ---- Compiles French version of CC90HFE ----

echo "Creating CC90HFE-console exec files for Windows setup in French..."

mingw32-make clean
mingw32-make RELEASE_MODE=1 CONSOLE_MODE=1
ren cc90hfe.exe cc90hfe-com.exe
copy cc90hfe-com.exe ..\..\misc\pack\mingw\fr
del  cc90hfe-com.exe

mingw32-make clean

cd ..
cd ..

echo "Create self-install files with Inno Setup now."

