@echo off

REM ---- Cleans executable files ----

if exist misc\pack\mingw\teow-*.exe    del misc\pack\mingw\teow-*.exe
if exist misc\pack\mingw\cc90hfe-*.exe del misc\pack\mingw\cc90hfe-*.exe

REM ---- Configures Teo sources for the Windows (MinGW) platform ----

echo "Configuring Teo sources for the Windows (MinGW) platform..."

echo # generated by mgwmake.bat > makefile
echo MAKEFILE_INC = makefile.mgw >> makefile
echo include makefile.all >> makefile

REM ---- Compiles English version of Teo ----

echo "Creating Teo exec files for Windows setup in English..."

mingw32-make clean
mingw32-make EN_LANG=1 PROFILEMODE=1
copy teow.exe misc\pack\mingw
ren misc\pack\mingw\teow.exe teow-en.exe

REM ---- Compiles French version of Teo ----

echo "Creating Teo exec files for Windows setup in French..."

mingw32-make clean
mingw32-make FR_LANG=1 PROFILEMODE=1
copy teow.exe misc\pack\mingw
ren misc\pack\mingw\teow.exe teow-fr.exe

mingw32-make depend
mingw32-make clean

REM ---- Compiles English version of CC90HFE ----

echo "Creating windowed CC90HFE exec files for Windows setup in English..."

cd tools
cd cc90hfe

echo Configuring CC90HFE sources for the Windows (MinGW) platform...
echo # generated by fixmingw.bat > makefile
echo MAKEFILE_INC = makefile.mgw >> makefile
echo include makefile.all >> makefile

mingw32-make clean
mingw32-make RELEASE_MODE=1 ENGLISH=1
copy cc90hfe.exe ..\..\misc\pack\mingw
ren ..\..\misc\pack\mingw\cc90hfe.exe cc90hfe-en.exe

REM ---- Compiles French version of CC90HFE ----

echo "Creating windowed CC90HFE exec files for Windows setup in French..."

mingw32-make clean
mingw32-make RELEASE_MODE=1
copy cc90hfe.exe ..\..\misc\pack\mingw
ren ..\..\misc\pack\mingw\cc90hfe.exe cc90hfe-fr.exe

REM ---- Compiles English version of CC90HFE ----

echo "Creating CC90HFE-console  exec files for Windows setup in English..."

mingw32-make clean
mingw32-make RELEASE_MODE=1 CONSOLE_MODE=1 ENGLISH=1
copy cc90hfe.exe ..\..\misc\pack\mingw
ren ..\..\misc\pack\mingw\cc90hfe.exe cc90hfe-com-en.exe

REM ---- Compiles French version of CC90HFE ----

echo "Creating CC90HFE-console exec files for Windows setup in French..."

mingw32-make clean
mingw32-make RELEASE_MODE=1 CONSOLE_MODE=1
copy cc90hfe.exe ..\..\misc\pack\mingw
ren ..\..\misc\pack\mingw\cc90hfe.exe cc90hfe-com-fr.exe

mingw32-make clean

cd ..
cd ..

echo "Create self-install files with Inno Setup now."
