#!/bin/sh

echo "Configuring CC90HFE sources for the Windows (MinGW) platform..."

echo "# generated by fixmingw.bat" > makefile
echo "MAKEFILE_INC = makefile.mgw" >> makefile
echo "include makefile.all" >> makefile

echo "Done!"
