#!/bin/bash

echo "Configuring CC90HFE sources for the Linux platform..."

echo "# generated by fixunix.sh" > makefile
echo "MAKEFILE_INC = makefile.lnx" >> makefile
echo "include makefile.all" >> makefile

echo "Done!"
